load locale by name and native name
houseabsolute/DateTime-Locale pull request #13
Opened 2017-02-20 10:34 UTC by sergle

Hi

According to the doc, DateTime::Locale->load($code) should be able to load by name: "The name provided may be either the English or native name.", but it doesn't.

2017-02-20 13:38 UTC, sergle commented
Build job 151.7 got stuck on TravisCI, trying to close/open pull request to restart the build.

2017-02-21 09:30 UTC, sergle commented
Still failing due to task timeout

2017-02-23 10:39 UTC, sergle commented
Again - all test are green, excluding Perl 5.14 which was just not started. :(

2017-02-25 05:44 UTC, preaction requested changes
Thanks for the patch! I would ask that you squash these commits into 1 commit before it gets merged into master: There's no real need for the perltidy/perlcritic changes to be their own commits. If you need help, [this article on squashing git commits might be helpful](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html), or just ask.

2017-02-27 14:18 UTC, sergle commented
@preaction As I understand it's possible to squash commits when pull request is merged (Squash and merge option on a pull request) but I cannot do it locally - it will not be possible to push changes. I have already tried commit amend earlier.
Please correct me if I'm wrong.

2017-02-27 18:06 UTC, preaction commented
Yes, you can squash commits locally. Once you rewrite history (which both `commit --amend` and `rebase -i` do), you must use `push --force` to update the remote PR branch.

2017-03-05 17:03 UTC, autarch commented
I merged this from the CLI. Thanks!

2017-03-05 17:03 UTC, closed without merging