Support custom locales with new register_data_locale function
houseabsolute/DateTime-Locale pull request #21
Opened 2018-04-11 17:10 UTC by ryleyb

Recent versions of DateTime::Locale no longer support subclassing
the DateTime::Locale::<locale> classes, as they do not exist.  The new
plan is to have users get a locale they want to modify from
DateTime::Locale->load, or create one from scratch, then they can
register it using the register_data_locale function.

Resolves https://github.com/houseabsolute/DateTime-Locale/issues/19

2018-04-12 01:05 UTC, autarch requested changes
Besides the things I noted this also needs some tests.

2018-04-12 01:05 UTC, autarch commented on lib/DateTime/Locale.pm
> +  my %data = %$locale;                          #copy the contents
We should add a method to get a copy of the data passed to the constructor, not encourage people to treat the object as a hashref. This also may means saving that data separately, since we store other computed data in the object as well.

2018-04-12 01:05 UTC, autarch commented on lib/DateTime/Locale.pm
> +    if ( ref $_[0] ) {
There's no need to support this being called as either a sub or method. Let's only support the method version.

2018-04-12 01:05 UTC, autarch commented on lib/DateTime/Locale.pm
> +C<< DateTime::Locale->register_data_locale() >>, C<<
But you're not clearing the cache, so this change is not correct. I don't think the cache needs to be cleared so the docs should be left as is.

2018-04-12 01:05 UTC, autarch commented on lib/DateTime/Locale/Data.pm
> +    $Codes{$code} = 1;
This should probably blow up if the code already exists.

2018-04-12 01:05 UTC, autarch commented on lib/DateTime/Locale/Data.pm
> +    $Names{ $data->{en_language} } = $code if exists $data->{en_language};
This has to exist. This probably needs some basic data validation.

2018-04-12 01:05 UTC, autarch commented on lib/DateTime/Locale/Data.pm
> +sub add_locale {
This should probably be private.

2018-04-12 01:05 UTC, autarch commented on lib/DateTime/Locale.pm
> +    my $id = $p{id};
All the references to "id" should be changed to "code".

2018-04-12 16:10 UTC, ryleyb commented on lib/DateTime/Locale.pm
> +C<< DateTime::Locale->register_data_locale() >>, C<<
FWIW, I was clearing the cache, but I will remove that along with this note!

2018-04-12 16:16 UTC, ryleyb commented on lib/DateTime/Locale.pm
> +  my %data = %$locale;                          #copy the contents
What shall we call this?  `locale_cldr_data` ?

2018-04-13 17:54 UTC, ryleyb commented on lib/DateTime/Locale/Data.pm
> +sub add_locale {
Since it's being used in DateTime::Locale, `tidyall` wasn't happy with that idea.  Am I missing something?

2018-06-08 16:49 UTC, autarch commented
Merged from the CLI. Thanks!

2018-06-08 16:49 UTC, closed without merging